name: Tesla Stock Checker Pro
on:
  schedule:
    - cron: '*/15 * * * *'  # 15 dakikada bir
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run Tesla Bot
        run: python tesla_bot.py
